### ISSUE TITLE
Images and databases not working

### ISSUE THREAD

**Issue by egleidson** [franklongford/PyFibre#19]
I installed the new version 2.0, using the steps in the Read.me file, but after finished I tried to run with one of my files and it didn't creates any image and did not saved the database file. 

The software appears to be running fine, it creates a folder for every image file with some of the metrics, and theses files has some data in it.

**Comment by franklongford** [comment]
Hi @egleidson - this issue should be fixed now.

Unfortunately I'm not able to include the fix in the latest release (2.0.0.dev) right away, but if you clone the repository and then checkout to the `dev` branch this should be implemented.

This can be achieved using the following command line steps (instead of downloading the release):

`git clone https://github.com/franklongford/PyFibre.git`

`git checkout dev`

Then go through the `PyFIbre` installation as normal to update the GUI. As you have already installed `edm`, you can probably just call:

`edm shell -e PyFibre-py36` (to enter the virtual environment)

`python -m ci install` (to update `PyFibre_GUI` with the fixes)

**Comment by franklongford** [comment]
Closed by #34
